#################################################################################
# Copyright (c) 2026 victor256sd
# All rights reserved.
#
#################################################################################
import streamlit as st
import streamlit_authenticator as stauth
import openai
from openai import OpenAI
import os
import time
import yaml
from yaml.loader import SafeLoader
from pathlib import Path
from cryptography.fernet import Fernet
import re
from st_copy import copy_button

# Define a dialog function
@st.dialog("Privacy Policy")
def privacy_popup():
    st.markdown("""
        **Permissions/Consent**<br>
        *When you submit a question, you consent to NASDTEC saving both your question and the response. The questions you ask won’t identify you, and you’ll remain anonymous. We are aware that someone may use this Chatbot to discuss a wide range of scenarios involving educators or other administrative topics. If an event is described, the Chatbot cannot determine if it is real or imagined. When you ask the Chatbot a question, you consent to our reviewing both the questions and answers to improve the Chatbot. After removing any inadvertent identifying information from any anonymous question, both answers and questions may be compiled for research, instructional, and publication purposes.*
    """, unsafe_allow_html=True)

# Disable the button called via on_click attribute.
def disable_button():
    st.session_state.disabled = True        

INSTRUCTION = ""
st.set_page_config(page_title="EDMSE Chatbot", page_icon=":butterfly:", layout="wide", initial_sidebar_state="collapsed")

st.markdown("""
<style>
[data-testid="stSidebarCollapseButton"] * {
    color: #1E90FF !important;
    fill: #1E90FF !important;
    stroke: #1E90FF !important;
}
[data-testid="stExpandSidebarButton"] * {
    color: #1E90FF !important;
    fill: #1E90FF !important;
    stroke: #1E90FF !important;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
    <style>
           /* Remove blank space at top and bottom */ 
           .block-container {
               padding-top: 2rem;
               padding-bottom: 0rem;
           }

    </style>
    """, unsafe_allow_html=True)

# st.markdown(
#     """
#     <h3 style="text-align: left; margin-top: 0;">
#         More Information
#     </h3>
#     """,
#     unsafe_allow_html=True
# )

# st.info("###### :arrow_upper_left: Click on the two blue arrows above for prompt writing pointers and other information in the sidebar.") #Access prompt writing pointers and other information in the sidebar.")
st.markdown(
    f"""
    <img src="https://raw.githubusercontent.com/victor256sd/mcee-gateway/main/image.png" alt="edmse" width=700 usemap="#workmap">
    <map name="workmap">
        <area shape="rect" coords="420,14,691,94" alt="nasdtec" href="https://www.nasdtec.net/" target="_blank">
        <area shape="rect" coords="499,105,630,236" alt="ncaee" href="http://www.educatorethics.org/" target="_blank">
    </map><br><br>        
    """,
    unsafe_allow_html=True
)    
# st.text("\n\n")
st.markdown("NASDTEC serves as a national advocate for the advancement of ethical practice within the education profession. To that end, the Model Code of Ethics for Educators (MCEE) was developed under NASDTEC’s leadership by a diverse and representative task force of educational practitioners and launched in 2015. Subsequently, NASDTEC established the National Council for the Advancement of Educator Ethics (NCAEE), which is charged with promoting and fostering awareness and understanding of the MCEE.")
st.markdown("**Disclaimer**:\n*This application was developed as a tool for practitioners to explore ethical dilemmas within the context of the MCEE and to stimulate discussions about ethical decision-making. Please understand that while the guidance and responses provided by this application are informed by the Model Code of Ethics for Educators, supportive resources, and related professional standards, they are generated by artificial intelligence. All AI-generated responses are intended for informational and educational purposes only and do not constitute legal advice, official policy interpretation, or a substitute for professional judgment. Users should consult their school district policies, state regulations, qualified professionals, or legal counsel for authoritative guidance on ethical or compliance matters. This tool is designed to assist, not replace, professional decision-making or formal review processes and may have inherent limitations, such as providing incomplete or inaccurate information.  Users of this app must not rely upon or make any decisions solely based on AI-generated responses to the questions asked. The answers provided are for consideration and thus are only a small part of the process of determining the best practices.*")
st.button("Privacy Policy", on_click=privacy_popup)
st.markdown("Review NASDTEC Ethics Chatbot: [link](https://www.surveymonkey.com/r/EDMSE)")

#-------------------------------------------------------
# Setup sidebar.
#-------------------------------------------------------
st.markdown("""
    <style>
    .top-text {
        position: fixed;
        top: -42.5px;
        left: -7px;
        padding: 55px;
        font-size: 24px;
        z-index: 999990; /* Keep it above other elements */
        pointer-events: none;
    }

    /* Hidden on desktop */
    .mobile-label {
        display: none;
    }

    @media (max-width: 768px) {
        .top-text {
            display: none;
        }
        .mobile-label {
            display: block !important;
            position: fixed;
            top: 19px;
            left: 45px;
            font-size: 14px;
            z-index: 999990;
        }
    }
    
    /* Add padding to the top of the main content so it doesn't overlap */
    .block-container {
        padding-top: 60px !important;
    }
    </style>
    <div class="top-text">
        More Information
    </div>
    <div class="mobile-label">
        More Information
    </div>
""", unsafe_allow_html=True)

st.sidebar.title("Additional Information")
st.divider()
st.sidebar.markdown("## Prompt Writing Pointers")
with st.sidebar.expander("1. Start with your role and the educational setting", expanded=False):
    st.markdown("""
        A strong prompt should tell the chatbot who you are and where the situation is happening.<br><br>
        Include details such as:<br>
            *“I am a student teacher…”*<br>
            *“I am a high school coach…”*<br>
            *“I am a special education teacher…”*<br>
            *“I work in a middle school team…”*<br>
            *“I teach in a rural community…”*<br><br>
        This helps the chatbot tailor the response to the educator’s professional responsibilities and boundaries.
    """, unsafe_allow_html=True)
with st.sidebar.expander("2. Describe the ethical dilemma with context", expanded=False):
    st.markdown("""
        Good prompts provide enough context for ethical reasoning without including names, personally identifiable information (PII), or details that could identify specific individuals. Focus on the circumstances, and ethical concerns rather than who the people are.<br><br>
        Instead of:<br>
            *"A student is in trouble. What do I do?"*<br>        
        Use:<br>
            *"A student regularly comes to school with bruising, but has not said anything about it. I am concerned about safety and do not want to make assumptions. What should I do?"*<br>        
        The chatbot tries to separate assumptions and values, and may state when information is missing or ambiguous.
    """, unsafe_allow_html=True)
with st.sidebar.expander("3. Name the ethical concerns you want addressed", expanded=False):
    st.markdown("""
        The best prompts identify the issues the user is worried about.<br><br>
        Useful ethical concern words include:<br>
        :black_small_square: professional boundaries<br>
        :black_small_square: confidentiality<br>
        :black_small_square: student safety<br>
        :black_small_square: equity<br>
        :black_small_square: bias<br>
        :black_small_square: academic integrity<br>
        :black_small_square: transparency<br>
        :black_small_square: documentation<br>
        :black_small_square: reporting obligations<br>
        :black_small_square: cultural sensitivity<br>
        :black_small_square: multiple relationships<br>
        :black_small_square: conflicts of interest<br>
        :black_small_square: school or district policy<br><br>
        This helps the chatbot produce structured, practical, and MCEE-grounded guidance.
    """, unsafe_allow_html=True)
with st.sidebar.expander("4. Ask the chatbot to use the MCEE and provide practical next steps", expanded=False):
    st.markdown("""
        Strong prompts should explicitly ask for MCEE-based reasoning.<br><br>
        A useful phrase is:<br>
            *"How should I respond ethically using the Model Code of Ethics for Educators? Please include relevant MCEE principles, practical next steps, and what information could change the assessment."*<br>        
        This aligns directly with the chatbot’s intention to lead with the MCEE when relevant.
    """, unsafe_allow_html=True)
with st.sidebar.expander("5. Ask for uncertainty, alternatives, and escalation points", expanded=False):
    st.markdown("""
        A strong ethics prompt should not just ask, “What should I do?” It should ask the chatbot to explain:<br>
        :black_small_square: *"what is clear"*<br>
        :black_small_square: *"what is uncertain"*<br>
        :black_small_square: *"what additional facts matter"*<br>
        :black_small_square: *"when to consult a supervisor, counselor, administrator, licensing authority, or state policy"*<br>
        :black_small_square: *"what actions may create risk"*<br><br>
        For example:<br>
            *"Please explain what information is missing, what could change the ethical assessment, and when I should consult administration or follow district reporting procedures."*<br><br>
        This matches the chatbot’s attempt to avoid overconfidence, acknowledge ambiguity, identify escalation points, and provide reasoning that could withstand review or professional scrutiny.        
    """, unsafe_allow_html=True)

st.sidebar.markdown("## Recently Asked")
with st.sidebar.expander("Questions", expanded=False):
    st.markdown(":black_small_square: How should I respond when a student uses AI on an assignment?")
    st.markdown(":black_small_square: Should I accept a gift from a family?")
    st.markdown(":black_small_square: What should I do if I observe a colleague acting unethically?")
    st.markdown(":black_small_square: How can I use AI responsibly in my classroom?")


st.sidebar.markdown("## Most Common Topics")
with st.sidebar.expander("Topics", expanded=False):
    st.markdown(":black_small_square: Technology & AI")
    st.markdown(":black_small_square: Social media")
    st.markdown(":black_small_square: Student safety")
    st.markdown(":black_small_square: Professional boundaries")
    st.markdown(":black_small_square: Parent relationships")
    st.markdown(":black_small_square: Professional boundaries")
    st.markdown(":black_small_square: Equity and fairness")

#-------------------------------------------------------

# Initialize state once
if "cleaned_response" not in st.session_state:
    st.session_state.cleaned_response = None

if "file_list_str" not in st.session_state:
    st.session_state.file_list_str = None

# Create new form to search aitam library vector store.    
with st.form(key="qa_form", clear_on_submit=False, height=300):
    query = st.text_area("**What would you like to discuss?**", height="stretch")
    submit = st.form_submit_button("Send")
    
# If submit button is clicked, query the aitam library.            
if submit:
    # If form is submitted without a query, stop.
    if not query:
        st.error("Enter a question for MCEE guidance!")
        st.stop()            

    with st.spinner('Thinking...'):
        cleaned_response = """
            ## :warning: EXAMPLE RESPONSE ONLY
            ### Key Guidelines Based on the Model Code of Ethics for Educators:
            ### Maintain Professional Responsibility
            AI can help organize thoughts or generate draft language, but educators remain responsible for the accuracy, fairness, and completeness of all communications with students and families.
            Review and edit all AI-generated content before sharing it.
            
            ### Protect Student Privacy
            Do not enter personally identifiable student information into public AI systems unless your school or district has approved the tool and appropriate privacy safeguards are in place.
            Follow applicable district policies and student data protection requirements.
            
            ### Ensure Fairness and Equity
            Be mindful of potential bias in AI-generated content.
            Verify that report language is respectful, inclusive, and free from stereotypes or assumptions.
            
            ### Prioritize Student Well-Being
            Reports should reflect professional judgment and support student growth.
            Avoid language that could unfairly label, stigmatize, or discourage students.
            
            ### Maintain Transparency
            Follow district expectations regarding disclosure of AI use.
            Consider being transparent with supervisors or stakeholders when AI substantially assists professional work.
            
            **Ethical Recommendation**: Use AI as a support tool rather than a decision-maker. Educators should rely on their professional expertise, knowledge of the student, and ethical obligations when preparing progress reports.        
        """
    # Persist response across refreshes/reruns
    st.session_state.cleaned_response = cleaned_response

if st.session_state.cleaned_response:
    st.markdown(st.session_state.cleaned_response)
    
    st.markdown("For additional information and resources, please visit [www.educatorethics.org](http://www.educatorethics.org).")
    
    # Add a small copy icon button
    copy_button(
        text=st.session_state.cleaned_response,
        tooltip="Copy this text",
        copied_label="Copied!",
        icon="st",
    )
